package pojos;
// Generated Nov 8, 2018 12:24:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Motor generated by hbm2java
 */
public class Motor  implements java.io.Serializable {


     private String platNomor;
     private String jenis;
     private String warna;
     private String status;
     private Set<Pesanan> pesanans = new HashSet<Pesanan>(0);

    public Motor() {
    }

	
    public Motor(String platNomor, String jenis, String warna, String status) {
        this.platNomor = platNomor;
        this.jenis = jenis;
        this.warna = warna;
        this.status = status;
    }
    public Motor(String platNomor, String jenis, String warna, String status, Set<Pesanan> pesanans) {
       this.platNomor = platNomor;
       this.jenis = jenis;
       this.warna = warna;
       this.status = status;
       this.pesanans = pesanans;
    }
   
    public String getPlatNomor() {
        return this.platNomor;
    }
    
    public void setPlatNomor(String platNomor) {
        this.platNomor = platNomor;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Pesanan> getPesanans() {
        return this.pesanans;
    }
    
    public void setPesanans(Set<Pesanan> pesanans) {
        this.pesanans = pesanans;
    }




}


