package pojos;
// Generated Nov 5, 2018 5:26:13 PM by Hibernate Tools 4.3.1



/**
 * Motor generated by hbm2java
 */
public class Motor  implements java.io.Serializable {


     private String platNomor;
     private String jenis;
     private String warna;
     private String status;

    public Motor() {
    }

    public Motor(String jenis, String warna, String platNomor, String status) {
       this.platNomor = platNomor;
       this.jenis = jenis;
       this.warna = warna;
       this.status = status;
    }
   
    public String getPlatNomor() {
        return this.platNomor;
    }
    
    public void setPlatNomor(String platNomor) {
        this.platNomor = platNomor;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


