package pojos;
// Generated Nov 12, 2018 4:23:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Penyewa generated by hbm2java
 */
public class Penyewa  implements java.io.Serializable {


     private int noIdentitas;
     private String nama;
     private int noHp;
     private String alamat;
     private Set<Pesanan> pesanans = new HashSet<Pesanan>(0);

    public Penyewa() {
    }

	
    public Penyewa(int noIdentitas, String nama, int noHp, String alamat) {
        this.noIdentitas = noIdentitas;
        this.nama = nama;
        this.noHp = noHp;
        this.alamat = alamat;
    }
    public Penyewa(int noIdentitas, String nama, int noHp, String alamat, Set<Pesanan> pesanans) {
       this.noIdentitas = noIdentitas;
       this.nama = nama;
       this.noHp = noHp;
       this.alamat = alamat;
       this.pesanans = pesanans;
    }
   
    public int getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(int noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(int noHp) {
        this.noHp = noHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set<Pesanan> getPesanans() {
        return this.pesanans;
    }
    
    public void setPesanans(Set<Pesanan> pesanans) {
        this.pesanans = pesanans;
    }




}


