package pojos;
// Generated Nov 7, 2018 3:01:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Penyewa generated by hbm2java
 */
public class Penyewa  implements java.io.Serializable {


     private String noIdentitas;
     private String nama;
     private String noHp;
     private String alamat;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Penyewa() {
    }

	
    public Penyewa(String nama, String noIdentitas, String noHp, String alamat) {
        this.noIdentitas = noIdentitas;
        this.nama = nama;
        this.noHp = noHp;
        this.alamat = alamat;
    }
    public Penyewa(String nama, String noIdentitas, String noHp, String alamat, Set<Transaksi> transaksis) {
       this.noIdentitas = noIdentitas;
       this.nama = nama;
       this.noHp = noHp;
       this.alamat = alamat;
       this.transaksis = transaksis;
    }
   
    public String getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(String noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


