package pojos;
// Generated Nov 6, 2018 12:40:46 PM by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private String noIdentitas;
     private Motor motor;
     private String nama;
     private String noHp;
     private String alamat;
     private String lamaSewa;
     private Date tanggalMulai;
     private Date tanggalSelesai;
     private Time jamPengantaran;
     private Time jamPenjemputan;
     private String jenisMotor;
     private String warna;
     private String platNomor;
     private String status;

    public Pesanan() {
    }

	
    public Pesanan(Motor motor) {
        this.motor = motor;
    }
    public Pesanan(Motor motor, String nama, String noHp, String alamat, String lamaSewa, Date tanggalMulai, Date tanggalSelesai, Time jamPengantaran, Time jamPenjemputan, String jenisMotor, String warna, String platNomor, String status) {
       this.motor = motor;
       this.nama = nama;
       this.noHp = noHp;
       this.alamat = alamat;
       this.lamaSewa = lamaSewa;
       this.tanggalMulai = tanggalMulai;
       this.tanggalSelesai = tanggalSelesai;
       this.jamPengantaran = jamPengantaran;
       this.jamPenjemputan = jamPenjemputan;
       this.jenisMotor = jenisMotor;
       this.warna = warna;
       this.platNomor = platNomor;
       this.status = status;
    }
   
    public String getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(String noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public Motor getMotor() {
        return this.motor;
    }
    
    public void setMotor(Motor motor) {
        this.motor = motor;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getLamaSewa() {
        return this.lamaSewa;
    }
    
    public void setLamaSewa(String lamaSewa) {
        this.lamaSewa = lamaSewa;
    }
    public Date getTanggalMulai() {
        return this.tanggalMulai;
    }
    
    public void setTanggalMulai(Date tanggalMulai) {
        this.tanggalMulai = tanggalMulai;
    }
    public Date getTanggalSelesai() {
        return this.tanggalSelesai;
    }
    
    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }
    public Time getJamPengantaran() {
        return this.jamPengantaran;
    }
    
    public void setJamPengantaran(Time jamPengantaran) {
        this.jamPengantaran = jamPengantaran;
    }
    public Time getJamPenjemputan() {
        return this.jamPenjemputan;
    }
    
    public void setJamPenjemputan(Time jamPenjemputan) {
        this.jamPenjemputan = jamPenjemputan;
    }
    public String getJenisMotor() {
        return this.jenisMotor;
    }
    
    public void setJenisMotor(String jenisMotor) {
        this.jenisMotor = jenisMotor;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getPlatNomor() {
        return this.platNomor;
    }
    
    public void setPlatNomor(String platNomor) {
        this.platNomor = platNomor;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


