package pojos;
// Generated Nov 1, 2018 11:39:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private String platNomor;
     private String nama;
     private Integer noIdentitas;
     private Integer noHp;
     private String lamaSewa;
     private Date tanggalMulai;
     private Date tanggalSelesai;
     private Date jamPengantaran;
     private Date jamPenjemputan;
     private String jenisMotor;
     private String warna;
     private String status;

    public Pesanan() {
    }

	
    public Pesanan(String platNomor) {
        this.platNomor = platNomor;
    }
    public Pesanan(String platNomor, String nama, Integer noIdentitas, Integer noHp, String lamaSewa, Date tanggalMulai, Date tanggalSelesai, Date jamPengantaran, Date jamPenjemputan, String jenisMotor, String warna, String status) {
       this.platNomor = platNomor;
       this.nama = nama;
       this.noIdentitas = noIdentitas;
       this.noHp = noHp;
       this.lamaSewa = lamaSewa;
       this.tanggalMulai = tanggalMulai;
       this.tanggalSelesai = tanggalSelesai;
       this.jamPengantaran = jamPengantaran;
       this.jamPenjemputan = jamPenjemputan;
       this.jenisMotor = jenisMotor;
       this.warna = warna;
       this.status = status;
    }
   
    public String getPlatNomor() {
        return this.platNomor;
    }
    
    public void setPlatNomor(String platNomor) {
        this.platNomor = platNomor;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(Integer noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public Integer getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(Integer noHp) {
        this.noHp = noHp;
    }
    public String getLamaSewa() {
        return this.lamaSewa;
    }
    
    public void setLamaSewa(String lamaSewa) {
        this.lamaSewa = lamaSewa;
    }
    public Date getTanggalMulai() {
        return this.tanggalMulai;
    }
    
    public void setTanggalMulai(Date tanggalMulai) {
        this.tanggalMulai = tanggalMulai;
    }
    public Date getTanggalSelesai() {
        return this.tanggalSelesai;
    }
    
    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }
    public Date getJamPengantaran() {
        return this.jamPengantaran;
    }
    
    public void setJamPengantaran(Date jamPengantaran) {
        this.jamPengantaran = jamPengantaran;
    }
    public Date getJamPenjemputan() {
        return this.jamPenjemputan;
    }
    
    public void setJamPenjemputan(Date jamPenjemputan) {
        this.jamPenjemputan = jamPenjemputan;
    }
    public String getJenisMotor() {
        return this.jenisMotor;
    }
    
    public void setJenisMotor(String jenisMotor) {
        this.jenisMotor = jenisMotor;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


