package pojos;
// Generated Nov 7, 2018 3:01:35 PM by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.Date;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Integer idTransaksi;
     private Motor motor;
     private Penyewa penyewa;
     private String lamaSewa;
     private Date tanggalMulai;
     private Date tanggalSelesai;
     private Time jamPengantaran;
     private Time jamPenjemputan;
     private String jenisMotor;
     private String warna;
     private String status;

    public Transaksi() {
    }

	
    public Transaksi(Penyewa penyewa, String lamaSewa, Date tanggalMulai, Time jamPengantaran, String jenisMotor, Motor motor, String warna, String status) {
        this.motor = motor;
        this.penyewa = penyewa;
        this.lamaSewa = lamaSewa;
        this.tanggalMulai = tanggalMulai;
        this.jamPengantaran = jamPengantaran;
        this.jenisMotor = jenisMotor;
        this.warna = warna;
        this.status = status;
    }
    public Transaksi(Penyewa penyewa, String lamaSewa, Date tanggalMulai, Date tanggalSelesai, Time jamPengantaran, Time jamPenjemputan, String jenisMotor, Motor motor, String warna, String status) {
       this.motor = motor;
       this.penyewa = penyewa;
       this.lamaSewa = lamaSewa;
       this.tanggalMulai = tanggalMulai;
       this.tanggalSelesai = tanggalSelesai;
       this.jamPengantaran = jamPengantaran;
       this.jamPenjemputan = jamPenjemputan;
       this.jenisMotor = jenisMotor;
       this.warna = warna;
       this.status = status;
    }
   
    public Integer getIdTransaksi() {
        return this.idTransaksi;
    }
    
    public void setIdTransaksi(Integer idTransaksi) {
        this.idTransaksi = idTransaksi;
    }
    public Motor getMotor() {
        return this.motor;
    }
    
    public void setMotor(Motor motor) {
        this.motor = motor;
    }
    public Penyewa getPenyewa() {
        return this.penyewa;
    }
    
    public void setPenyewa(Penyewa penyewa) {
        this.penyewa = penyewa;
    }
    public String getLamaSewa() {
        return this.lamaSewa;
    }
    
    public void setLamaSewa(String lamaSewa) {
        this.lamaSewa = lamaSewa;
    }
    public Date getTanggalMulai() {
        return this.tanggalMulai;
    }
    
    public void setTanggalMulai(Date tanggalMulai) {
        this.tanggalMulai = tanggalMulai;
    }
    public Date getTanggalSelesai() {
        return this.tanggalSelesai;
    }
    
    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }
    public Time getJamPengantaran() {
        return this.jamPengantaran;
    }
    
    public void setJamPengantaran(Time jamPengantaran) {
        this.jamPengantaran = jamPengantaran;
    }
    public Time getJamPenjemputan() {
        return this.jamPenjemputan;
    }
    
    public void setJamPenjemputan(Time jamPenjemputan) {
        this.jamPenjemputan = jamPenjemputan;
    }
    public String getJenisMotor() {
        return this.jenisMotor;
    }
    
    public void setJenisMotor(String jenisMotor) {
        this.jenisMotor = jenisMotor;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


