package pojos;
// Generated Nov 26, 2018 5:25:42 PM by Hibernate Tools 4.3.1



/**
 * Penyewa generated by hbm2java
 */
public class Penyewa  implements java.io.Serializable {


     private String noIdentitas;
     private String nama;
     private String noHp;
     private String alamat;

    public Penyewa() {
    }

    public Penyewa(String noIdentitas, String nama, String noHp, String alamat) {
       this.noIdentitas = noIdentitas;
       this.nama = nama;
       this.noHp = noHp;
       this.alamat = alamat;
    }
   
    public String getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(String noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


